suite('invalid-definitions', () => {
  require('./name')
  require('./root-schema')
  require('./flipped-from')
  require('./merge-definition-with')
  require('./expected-support-argument-types')
  require('./function-props')
  require('./groups')
  require('./data-dependent-props')
  require('./has-no-data-argument')
})
